### ISSUE TITLE
URL-safe Base64 support

### ISSUE THREAD

**Issue by cedrickcooke** [JuulLabs/tuulbox#152]

**Comment by twyatt** [comment]
With [Base64 support coming to the standard library](https://kotlinlang.org/docs/whatsnew-eap.html#experimental-support-for-base64-encoding-in-standard-library), there probably isn't any need for us to maintain the Tuulbox support.

I'll create a PR shortly that marks Tuulbox's Base64 support as deprecated.

**Comment by twyatt** [comment]
Marked Tuulbox's Base64 functions as deprecated via #239.

**Comment by twyatt** [comment]
Closing as we don't plan to maintain base64 (in favor of official support).
