### ISSUE TITLE
Failed building KotlinMPPGradleModel

### ISSUE THREAD

**Issue by francismariano** [JuulLabs/tuulbox#77]
Hello folks

i'm trying to add the library into my KMM project and i'm having problem syncing the files.

```
val commonMain by getting {
        dependencies {
            implementation("com.juul.tuulbox:logging:4.2.0")
        }
    }
```

When the project syncs I get the following error:

```
Failed building KotlinMPPGradleModel
org.gradle.internal.resolve.ArtifactNotFoundException: Could not find logging-4.2.0-samplessources.jar (com.juul.tuulbox:logging:4.2.0).
Searched in the following locations:
    https://repo.maven.apache.org/maven2/com/juul/tuulbox/logging/4.2.0/logging-4.2.0-samplessources.jar
	at org.gradle.internal.resolve.result.DefaultBuildableArtifactResolveResult.notFound(DefaultBuildableArtifactResolveResult.java:28)

.......
```

It could be something related to that https://youtrack.jetbrains.com/issue/KTIJ-10769 ?????

Thank you

**Comment by twyatt** [comment]
Thanks for the YouTrack link, based on the discussion in the issue, it sounds like you may be targeting more platforms that Tuulbox logging currently provides?

What platforms are you targeting in your project?

**Comment by francismariano** [comment]
Sorry for the delay.
Answering your question : 

commonMain
androidMain
iosX64Main
iosArm64Main

Kable works fine.

**Comment by twyatt** [comment]
Android support is planned (#74).

As a workaround, you can use the JVM artifact in your Android target for now:

```
val androidMain by getting {
    dependencies {
        implementation("com.juul.tuulbox:logging-jvm:4.2.0")
    }
}
```

Unfortunately, I believe you'll also have remove the `tuulbox:logging` dependency from `commonMain` and specify it for each target, which is pretty cumbersome.

**Comment by twyatt** [comment]
Strange, we were able to use Tuulbox logging in `commonMain` without the issue you're seeing: https://github.com/JuulLabs/sensortag/blob/4478a9e3f70ef5ef80ac6b99e256686fcf594ec0/app/build.gradle.kts

**Comment by francismariano** [comment]
Kotlin version is 1.5.21 and gradle-7.1-bin

With gradle 6.5 I get another exception:
```
* Exception is:
org.gradle.api.GradleException: Please initialize at least one Kotlin target in 'shared (:shared)'.
```

**Comment by twyatt** [comment]
> Kotlin version is 1.5.21 and gradle-7.1-bin
> 
> I get another exception with gradle 6.5 :
> 
> ```
> * Exception is:
> org.gradle.api.GradleException: Please initialize at least one Kotlin target in 'shared (:shared)'.
> ```

Are you saying that it works with the latest Gradlew but not with Gradle 6.5? Is there something keeping you on the older Gradle version.

Sorry, but I'm not sure we have the resources to support older Gradle versions. Happy to help debug if you have issues with the latest Gradle.

**Comment by francismariano** [comment]
Hello Travis.

It did not work with gradle 6.5, 7.1 and 7.1.1

I just created a new project and adding tuulbox:logging on commonMain dependencies. I get the exception when I try sync the project.

**Comment by twyatt** [comment]
> It did not work with gradle 6.5, 7.1 and 7.1.1

Thanks for clarifying. Not working in the latest Gradle version is definitely a problem we need to fix.

Do you happen to have a project that reproduced this issue that you can share? If not, perhaps you can share the Gradle config?

**Comment by francismariano** [comment]
Travis

https://github.com/francismariano/tullbox-logging-issue-77

The project reproduced this issue. It is a blank project with only tullbox logging added.

**Comment by twyatt** [comment]
Thanks for providing the repo link. We're swamped on some other tasks at the moment, but I'll take a look at this when I have a free moment.

**Comment by twyatt** [comment]
@francismariano can you try `4.5.3-SNAPSHOT` and let us know if it resolves your issue? Thank you!

```
repositories {
    maven("https://oss.sonatype.org/content/repositories/snapshots")
}

dependencies {
    implementation("com.juul.tuulbox:$artifactId:4.5.3-SNAPSHOT")
}
```

**Comment by francismariano** [comment]
I'm sorry for the delay in replying.

The 4.5.3-SNAPSHOT worked like a charm. The most recent version works as well.
Thank you.
